# Generated by Django 6.0.3 on 2026-03-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy1', models.CharField(max_length=50)),
                ('strategy2', models.CharField(max_length=50)),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('rounds', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
