# Generated by Django 6.0.3 on 2026-03-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='noise',
            field=models.FloatField(default=0),
        ),
    ]
